[versions]
libraryVersion = "0.0.1"
compilesdk = "34"
minsdk = "26"
targetsdk = "33"
java = "17"


agp = "8.3.2"
kotlin = "1.9.23"
# Kotlinter version is tied closely to min & max Kotlin and Gradle versions. Update Kotlinter
# when updating Kotlin. Check compatible versions here:
# https://github.com/jeremymailen/kotlinter-gradle/blob/master/README.md#compatibility
kotlinter = "3.15.0"
#kotlinter = "4.3.0"
# Check kotlin-compose compiler compatibility chart here:
# https://developer.android.com/jetpack/androidx/releases/compose-kotlin
compose-compiler = "1.5.11"

activity = "1.8.2"
appcompat = "1.6.1"
composeBom = "2024.04.00"
composeLint = "0.1.10"
coreKtx = "1.12.0"
detekt = "1.23.6"
inject = "1"
kotlinx-collections-immutable = "0.3.7"
lifecycleRuntimeKtx = "2.7.0"
lint-gradle = "1.0.0-alpha01"
timber = "5.0.1"

junit = "4.13.2"
espressoCore = "3.5.1"
androidx-junit = "1.1.5"
androidx-test-core = "1.5.0"
androidx-test-rules = "1.5.0"
androidx-test-runner = "1.5.2"
testparameterinjector = "1.15"
paparazzi = "1.3.3"

# Convention plugin versions
guardian-convention-plugins = "1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-ripple = { group = "androidx.compose.material", name = "material-ripple" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSize = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-uiTest = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "lint-gradle" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
other-timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
google-testParameterInjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }

# These rules are now maintained independently by Nacho Lopez who originally created them at
# Twitter: https://github.com/mrmans0n/compose-rules
other-composeLint = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "composeLint" }

[plugins]

android-lint = { id = "com.android.lint", version.ref = "agp"}
agp-application = { id = "com.android.application", version.ref = "agp" }
kgp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
agp-library = { id = "com.android.library", version.ref = "agp" }
agp-test = { id = "com.android.test", version.ref = "agp" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

# Guardian's convention plugins
guardian-application = { id = "com.theguardian.application", version.ref = "guardian-convention-plugins" }
guardian-library-android = { id = "com.theguardian.library.android", version.ref = "guardian-convention-plugins" }
guardian-test-android = { id = "com.theguardian.test.android", version.ref = "guardian-convention-plugins" }
guardian-library-kotlin = { id = "com.theguardian.library.kotlin", version.ref = "guardian-convention-plugins" }
guardian-compose-library = { id = "com.theguardian.compose.library", version.ref = "guardian-convention-plugins" }
guardian-compose-application = { id = "com.theguardian.compose.application", version.ref = "guardian-convention-plugins" }
guardian-detekt = { id = "com.theguardian.detekt", version.ref = "guardian-convention-plugins" }